### ISSUE TITLE
Import Danfo.js functions

### ISSUE THREAD

**Issue by WenheLI** [imgcook/datacook#9]
Danfojs has a set of handy-dandy tabular data processing functions. We could also import them into datacook.
Thoughts & comments are welcome.

**Comment by yorkie** [comment]
Could this be fixed by ec6b4134bab3bf895ca81b4a39134b63cfa606af?

**Comment by risenW** [comment]
@WenheLI Are you still working on this? If not I could work on it later today as I am more conversant with danfo.js

**Comment by WenheLI** [comment]
> @WenheLI Are you still working on this? If not I could work on it later today as I am more conversant with danfo.js

😖 Sorry, I am involved in other things right now. If u could help me with it, it would be fantastic!

**Comment by risenW** [comment]
> > @WenheLI Are you still working on this? If not I could work on it later today as I am more conversant with danfo.js
> 
> 😖 Sorry, I am involved in other things right now. If u could help me with it, it would be fantastic!

No problem at all, I'll work on it
